# Generated by Django 2.2.13 on 2023-03-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='total',
        ),
    ]
