# Generated by Django 2.2.13 on 2023-03-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_livraison_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='status',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminé', 'Terminé'), ('annuler', 'Annuler')], max_length=10),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
    ]
