# Generated by Django 2.2.13 on 2023-04-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20230331_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='venue',
            new_name='ville',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='heure',
        ),
    ]
