# Generated by Django 2.2.13 on 2023-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20230403_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='telephone',
            field=models.CharField(max_length=8),
        ),
    ]
