# Generated by Django 2.2.13 on 2023-04-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20230403_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('abandonné', 'Abandonné'), ('bloqué', 'Bloqué')], max_length=10),
        ),
    ]
